version: '3'

services:
  db:
    image: postgres
  web:
    build: .
    command: gunicorn -w 4 -b 0.0.0.0:8000 app:app
    environment:
      - DB_DSN=postgresql://postgres@db:5432/postgres
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
